### ISSUE TITLE
jsuite not working with angular

### ISSUE THREAD

**Issue by kallaguntaashok** [jsuites/jsuites#109]
in below code i am binding dropdown, ondropdown change i am taking value and updating it into textbox, if I use this key word code won't work and also I am not able to pass the value to object.
`<div class="col-md-2">      
            <i class="bi bi-asterisk star"></i>
            <div #dropProjectMaster></div>
        </div>
        <div class="col-md-4">         
            <i class="bi bi-asterisk star"></i>   
            <input type="text" placeholder="Description" #ProjectDescription required name="ProjectDescription" [(ngModel)]="model.ProjectDescription"
             class="form-control form-control-sm">
        </div> 

@ViewChild('dropProjectMaster') dropProjectMaster: ElementRef;

initiateProjectMaster(){
    this.buildRequestService.getProjectMaster().subscribe((response) => {
      jSuiteProjectMaster = jsuites.dropdown(
        this.dropProjectMaster.nativeElement,
        {
          data: JSON.parse(response),          
          autocomplete: true,
          placeholder: 'Select Project ID',   
          onchange: this.updateProjectDescription,       
        }
      );  
    }, error => {
      console.log(error);
    })
  }
  updateProjectDescription(){
    //@ts-ignore
    var pmValue = jSuiteProjectMaster.getValue();    
    **this.model.ProjectDescription = pmValue** **// this line is not working, even if I add any typescript code it's not working with in jsuite code & jspreedsheet code to** 
  }`

**Comment by hodeware** [comment]
We are releasing the types in the next few days.
