### ISSUE TITLE
how to add html required tag to jsuite dropdown. 

### ISSUE THREAD

**Issue by kallaguntaashok** [jsuites/jsuites#110]
I am doing form validation, normal HTML controls are able to focus the input fields but jsuite dropdown doesn't support required fields.

required tag will make user to fill that area before click on submit, is there any way to add required field to it. 

![image](https://user-images.githubusercontent.com/26366259/148901340-ccba1f2e-84f5-4192-9bf1-0a62e1736938.png)

**Comment by hodeware** [comment]
you could use onload to add in the HTML.
