### ISSUE TITLE
jSuite Ajax call is showing unauthorized if Web api is having windows authentication. 

### ISSUE THREAD

**Issue by kallaguntaashok** [jsuites/jsuites#111]
my web-api is secured with windows authentication, client is angular app, to send windows credentials from app to webapi  "httpRequest.withCredentials = true;" we need to add the info in ajax call.

i add this jSuite.js file, it's working fine, but in future if you update library i will lose my code, could you please add this condition in your library. 

![image](https://user-images.githubusercontent.com/26366259/148901654-e141c508-bba8-47ed-91e5-71e3be7b223a.png)

**Comment by hodeware** [comment]
You can use beforeSend to include any headers.
