### ISSUE TITLE
Jexcel Issue

### ISSUE THREAD

**Issue by sonal-kothari-altius** [jsuites/jsuites#114]
When I type in a '0' before the number it doesn't show properly in the cell. So for example, it shows '4' if I type '4' but shows '0' if I type '04'
![Screenshot Capture - 2022-03-30 - 15-34-41](https://user-images.githubusercontent.com/61678249/160810451-cc41719f-83b2-4cb0-972e-0ab12e6d00db.png)

**Comment by hodeware** [comment]
That has been fixed. 4.11.2+

**Comment by sonal-kothari-altius** [comment]
Thanks for update. Its working fine now.
