### ISSUE TITLE
Missing styleheets

### ISSUE THREAD

**Issue by bleutzinn** [jsuites/jsuites#117]
I'm trying the example "JavaScript rich form" ( [https://jsuites.net/v4/rich-form/methods](https://jsuites.net/v4/rich-form/methods) ).

This is the start of your example source code:
```
<script src="https://jsuites.net/v4/jsuites.js"></script>
<link rel="stylesheet" href="https://jsuites.net/v4/jsuites.css" type="text/css" />
```

It seems to me that the stylesheet `jsuites.layout.css` should be included in this (and other) example(s) as well.

The source code of the page (see link above) also includes the stylesheet `jsuites.mobile.css` but that file is also not in the example source and is not included in the `dist` directory after a `npm jsuites install`.

**Comment by hodeware** [comment]
Sorry for the delay.

This particular plugin does requires the jsuites.css and jsuites.js only.

Really optional for the example.
https://cdn.jsdelivr.net/npm/@jsuites/css@1.0.9/dist/style.min.css
