### ISSUE TITLE
Replacing '\n' by '<br>' not working in example code

### ISSUE THREAD

**Issue by bleutzinn** [jsuites/jsuites#118]
I could not find any other way to contribute to the documentation so I raised this issue here.

The regex to replace newlines (`\n`) with `<br>` in notification messages shown in the example code on  https://jsuites.net/v4/rich-form/validations is not correct causing the replacement to fail.

Not working:
`message = message.replace(new RegExp(/\n/g), "<br>");`

Working:
`message = message.replace(new RegExp("\\\\n", "gm"), "<br>");`

**Comment by nicolasjesse** [comment]
Thank you for the suggestion! We've implemented the changes you proposed. Closing this issue now.
