### ISSUE TITLE
How can I remove (-) Sign when I am using masking for negative number?

### ISSUE THREAD

**Issue by sachiv-logiciel** [jsuites/jsuites#119]
Hi Team,

I am trying to use masking for accounting sign with negative number. It's append (-) a Sign with value, but if you follow the Excel behavior then it's display negative value, something like this (123) if my actual value is -123. Can you please suggest me some way to remove (-) sign in masking?

Mask: #,##0.00;(#,##0.00)

**Comment by hodeware** [comment]
composite masking only works along JSS. And there is no plans for implementing this on jsuites only.
