### ISSUE TITLE
Jsuites Tag doesn't work on Safari and Firefox

### ISSUE THREAD

**Issue by MathieuJDS** [jsuites/jsuites#129]
I am using Jsuites tags and it works perfectly with Chrome. But it doesn't on Firefox or Safari.

Firefox and Safari are on the last version

I am using this code to create the field:

```
jSuites.tags(document.querySelector('.tag-input-option1'), {
    validation: function(element, text, value) {
        if (! value) {
            value = text;
        }
        var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        var test = re.test(String(value).toLowerCase()) ? true : false;
        return true;
    }
});
```

And on chrome the system works properly

<img width="390" alt="backinthegame · WideBundle - Offers on product · Shopify 2022-10-31 19-14-09" src="https://user-images.githubusercontent.com/32767485/199080429-9634ef76-f2ba-4422-8cb4-0c25343ca33b.png">

But on Safari or Firefox when we start writing it doesn't create a tag

![image](https://user-images.githubusercontent.com/32767485/199080837-9327c56e-78ca-4c31-b141-a8e88eb57e30.png)

Here is an example in video for chrome where it works:

https://www.loom.com/share/1eebe9056b1748439cce86fbf6b0a9d4

And an example for Firefox where it doesn't work:

https://www.loom.com/share/baef9bd6e112495cafd8c3bf52577069

**Comment by hodeware** [comment]
Thanks a lot. That has been fixed.

**Comment by MathieuJDS** [comment]
Hey! Thank you! Can we get the update on: https://jsuites.net/v4/jsuites.js

Because for now it's still Version = '4.16.10'
