### ISSUE TITLE
Certificate expired for https://jsuites.net/v4/

### ISSUE THREAD

**Issue by k4a-l** [jsuites/jsuites#133]
https://jsuites.net/v4/

Expire at 2023-01-03 23:59:59 UTC.
Please update🙏

**Comment by hodeware** [comment]
That is updated. But, use this one... it will be much faster.
https://cdn.jsdelivr.net/npm/jsuites@4.17.7/dist/jsuites.min.js
https://cdn.jsdelivr.net/npm/jsuites@4.17.7/dist/jsuites.min.css

**Comment by k4a-l** [comment]
Thanks for the response and suggestions!
