### ISSUE TITLE
12-Hour Clock format in Calendar

### ISSUE THREAD

**Issue by e808080** [jsuites/jsuites#151]
We create a column with the following options:

`options: { format: 'MM/DD/YYYY HH12:MI AM/PM', time: 1 }`

It works and shows the time with 12H clock format but in the editor the choices are in 24 clock format. How can we configure it so the editor uses 12H clock? Thanks

![timeformat](https://github.com/jsuites/jsuites/assets/157099045/e516221c-7e55-468e-bc6c-ae38a970cf22)

**Comment by nicolasjesse** [comment]
Thank you for your suggestion! We've added this option, and it will be available in the next package version release in the coming days.

You'll be able to enable the 12-hour clock format by setting the following option:

`is24HourFormat: false`
