### ISSUE TITLE
Calendar automatically partially sets a date when the calendar opens

### ISSUE THREAD

**Issue by gtasker10** [jsuites/jsuites#152]
To see the problem, using your v5 example for calendar...

1) Open the page: https://jsuites.net/docs/javascript-calendar
2) Click the getValue() button, it shows there is no value. 
3) Click the calendar picker icon to open the calendar, then press ESC without picking a date
4) Click the getValue() button, it shows there is now a value when you call the .getValue() function, but the textbox does not show a date

The reason for this is when the calendar opens, the .open() function calls getDays().  The getDays() function for some reason directly changes the date to the current date (not calling setDate()):

`// Selection container`
`obj.date = [year, month, day, hour, min, 0];`

I would suggest that this line should not be there.  The getDays() function should not change the date

**Comment by nicolasjesse** [comment]
Thank you for your input! The issue has been resolved. If you encounter any further problems or have additional feedback, feel free to let us know.
