### ISSUE TITLE
Select & Edit

### ISSUE THREAD

**Issue by yeonjin35** [jsuites/jsuites#66]
Hi,
i love your jsuites. 
i have a question about drop-box.
Is there any way to use drop-box(select) & write together?
I know you support New Options.. but i want little bit different.
i want to select dropbox and write text about cells.
so if you support this function, could you please let me know about it?
Thank you.

**Comment by hodeware** [comment]
Sorry, it is not possible. The dropdown should be an existing option (even remote), or a new option added.
