### ISSUE TITLE
there is some small problem with remoteSearch

### ISSUE THREAD

**Issue by huangxianggui** [jsuites/jsuites#67]
if (obj.options.remoteSearch == true) {

the url should correct from:
                url: obj.options.url + '?q=' + str,
to:
                url: obj.options.url + (obj.options.url.indexOf('?') > 0 ? "&" : "?") + 'q=' + str,

the Result Display Should Correct from :
obj.appendData(result);
to:
obj.setData(result);

**Comment by hodeware** [comment]
I have fixed the URL, but not sure about setData... since it will reset all internal controls
