### ISSUE TITLE
Add Synonyms to dropdown autocomplete search (Feature Request)

### ISSUE THREAD

**Issue by JoshuaFortriede** [jsuites/jsuites#68]
Feature Request: 
When supplying the data for a dropdown, it would be very helpful to be able to include a synonym array that could be used to filter items when using the autocomplete feature. For instance, an entry in a countries list might be:

{"id":"US","name":"United States of America","synonym":["USA","US","America","USofA"]}

**Comment by hodeware** [comment]
Sounds interesting, we are going to include that in the next release. Thanks for your suggestion.

**Comment by hodeware** [comment]
It has been done, it is available on v4.4.4+
