### ISSUE TITLE
change event not working

### ISSUE THREAD

**Issue by lennygir** [jsuites/jsuites#69]
Hello, i'm trying to use jsuites dropdown into a webpack but i dont succeed to use events...
Is there a mistake ?
```js
this.dropdown = jSuites.dropdown(this.input, {
      data: countries,
      autocomplete: true,
      multiple: this.schema.multiple,
      lazyLoading: true,
      type: this.schema.typeInput,
      width: this.schema.width,
    });

    this.addEventListener(this.dropdown, 'change', () => {
      console.log("updated")
      this.updateValue()
    })
```

**Comment by joaovmvini** [comment]
the onchange method must be passed as an attribute of the jsuites dropdown.

`this.dropdown = jSuites.dropdown(this.input, {
      data: countries,
      autocomplete: true,
      multiple: this.schema.multiple,
      lazyLoading: true,
      type: this.schema.typeInput,
      width: this.schema.width,
      onchange: function(element, index, oldValue, newValue, oldLabel, newLabel) {
           console.log("updated");
      }
    });`

for more information access the jsuites [documentation](https://jsuites.net/v4/dropdown-and-autocomplete/quick-reference)

**Comment by joaovmvini** [comment]
the onchange method must be passed as an attribute of the jsuites dropdown.

```
this.dropdown = jSuites.dropdown(this.input, {
      data: countries,
      autocomplete: true,
      multiple: this.schema.multiple,
      lazyLoading: true,
      type: this.schema.typeInput,
      width: this.schema.width,
      onchange: function(element, index, oldValue, newValue, oldLabel, newLabel) {
           console.log("updated");
      }
});
```
for more information access the jsuites [documentation](https://jsuites.net/v4/dropdown-and-autocomplete/quick-reference)

**Comment by lennygir** [comment]
Owh, thank you very much, i missed that information ! Have a nice day
