### ISSUE TITLE
Add Definition to dropdown on hover (Feature Request)

### ISSUE THREAD

**Issue by JoshuaFortriede** [jsuites/jsuites#73]
**Feature Request:**
When hovering over a dropdown entity, have a "title" box that would display a "definition". 

List entity:
{
"id":"apple",
"name":"Apple",
"definition":"An apple is an edible fruit produced by an apple tree (Malus domestica)."
}

**Comment by supportdesk-si** [comment]
This is relatively easy.  Locate `obj.createItem = function ...` 

Insert this code after any `if (data....` block.
`if (data.definition) {
    item.element.title = data.definition;
}`

**Comment by hodeware** [comment]
We have added tooltip for this purpose.
