### ISSUE TITLE
dropdown groups fail on lazyload

### ISSUE THREAD

**Issue by supportdesk-si** [jsuites/jsuites#74]
Affects both 4.6.5 and 4.6.7
 When items are grouped, lazyload fails with error
`Uncaught TypeError: can't access property "appendChild", results[i].group.children[2] is undefined`

From quick lookup, the block responsible for the error is the one below. With the line of error being this:
`results[i].group.children[2].appendChild(results[i].element);`

			for (var i = numberOfItems; i < numberOfItems + number; i++) {
				if (results[i].group) {
					if (! results[i].group.parentNode) {
						content.appendChild(results[i].group);
					}
					results[i].group.children[2].appendChild(results[i].element);
				} else {
					content.appendChild(results[i].element);
				}

				obj.numOfItems++;
			}

**Comment by hodeware** [comment]
it has been fixed.
