### ISSUE TITLE
Uncaught DOMException on jSuites.loading.hide

### ISSUE THREAD

**Issue by basteks** [jsuites/jsuites#86]
Hi ! 
in jSpreadsheet, with the loadingSpin activated, I see an error in the javascript console when jSuites try to hide the loadingSpin : 
`Uncaught DOMException : The node to be removed is not a child of this node`
Apparently, the code passes twice in the `hide()` function, so first time `document.body.removeChild(loading);` works, but second time (loading element still exists but is no longer a child of body element) it triggers the error.
A simple workaround is to modify the test in the `hide()` function : I replaced `if (loading)` by `if (loading && loading.parentElement)`, maybe it could be integrated.
Bests,

**Comment by hodeware** [comment]
Something similar is already implemented, please consider upgrading to a newer version.
