### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'length' of function

### ISSUE THREAD

**Issue by dd-condat** [jsuites/jsuites#89]
I there! Currently i'm getting the following error after loading the jsuites.js (Version: 4.7.3):

`jsuites.js?1626333788:10176 Uncaught TypeError: Cannot assign to read only property 'length' of function 'function(value, options) {
    if (typeof(jSuites.validations[options.type]) === 'function') {
        return j...<omitted>...
}'
    at jsuites.js?1626333788:10176
    at jsuites.js?1626333788:13
    at jsuites.js?1626333788:14
(anonymous) @ jsuites.js?1626333788:10176
(anonymous) @ jsuites.js?1626333788:13
(anonymous) @ jsuites.js?1626333788:14`

**Comment by hodeware** [comment]
Please upgrade to 4.7.4
