### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [jsuites/jsuites#92]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.

**Comment by hodeware** [comment]
Sure, I have invited you.

**Comment by intrigus-lgtm** [comment]
Closing because https://github.com/jsuites/jsuites/security/advisories/GHSA-qh7x-j4v8-qw5w has been created.
