### ISSUE TITLE
Security vulnerability report

### ISSUE THREAD

**Issue by pwntester** [jsuites/jsuites#94]
Hello,

The GitHub Security Lab team has found a potential vulnerability in jSuites text editor. We tried contacting `contact@jsuites.net` but got the email bounced. Please create a Security Advisory and invite me (pwntester) in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a Security Policy containing a security email address to send the details to.

If you prefer to contact us by email, please reach out to securitylab@github.com with reference to GHSL-2021-1002.

Kind regards,
Alvaro Muñoz
GitHub Security Lab

**Comment by hodeware** [comment]
We are working on the necessary fixes, but we have sent you invitation.

**Comment by pwntester** [comment]
Thanks @hodeware that was the very same issue found by our team. Will follow up the discussion in the advisory

**Comment by pwntester** [comment]
Hi @hodeware can you please credit @bananabr and @erik-krogh on https://github.com/jsuites/jsuites/security/advisories/GHSA-qh7x-j4v8-qw5w as they also found the issue independently
