### ISSUE TITLE
Control modal separately

### ISSUE THREAD

**Issue by francofgp** [jsuites/jsuites#99]
I have the following issue:
When I create the first modal, everything works fine, but when I open the second one, and I want to move or close the first one I get undefined, it is like the second modal overrides the first one, and I have to close the second one and  open the first to gain control again.
The content of both modals works fine with both modals open at the same time, it is just the onclose function that doesn´t work and the option to move it with the mouse

So my question is: is there a way to have like to different instance of a modal?

I had tried using as a [WebComponent](https://jsuites.net/v4/modal) and as the [Basic example](https://jsuites.net/v4/modal/basic)
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/70602890/136973520-f78e3e18-77d9-45f0-887d-4bb9ad240a7e.gif)

**Comment by paulhodel** [comment]
Sorry about the delay. But, we were not able to replicate this problem. Both vanilla and web component works independently.
https://jsfiddle.net/spreadsheet/o9p23kah/
Can you send a jsfiddle example?

**Comment by paulhodel** [comment]
That has been fixed.

**Comment by hodeware** [comment]
It has been fixed.

**Comment by francofgp** [comment]
Thanks Keep up the good work. 👍
